### ISSUE TITLE
inzynierką bys sie zajął a nie

### ISSUE THREAD

**Issue by osdnk** [tchayen/cra-with-ssr#1]
@tchayen

**Comment by tchayen** [comment]
Thank you for your concern regarding this piece of OSS. I am deeply committed to providing the best quality possible. However, I believe my time resources are too constrained at the particular moment and I have to close this issue for now.

Thank you for your time!

**Comment by osdnk** [comment]
@osdnk 
Could you please reopen? I believe that many users can approach similar questions.
